apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: docker.adeo.no:5000/soknadsfillager
  port: 9042
  liveliness:
    path: /soknadsfillager/internal/isAlive
    initialDelay: 5
  readiness:
    path: /soknadsfillager/internal/isReady
    initialDelay: 5
  prometheus:
    path: /soknadsfillager/internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enable: true