apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveliness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsfillager.nais.adeo.no"
    - "https://soknadsfillager.prod-fss.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
  env:
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
    - name: DATABASE_HOST
      value: a01dbfl039.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: soknadsfillager-db
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
