apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "320M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
spec:
  image: {{image}}
  port: 9042
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1 # TODO: change to 2 when the consistency check is completed
    max: 1 # TODO: change to 4 when the consistency check is completed
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingress}}
    - "{{this}}"
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: {{ database-name }}
            envVarPrefix: DATABASE
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        {{#each inbound}}
        - application: "{{this}}"
        {{/each}}
        - application: soknadsmottaker # TODO: This is a temporary consistency check

  envFrom:
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{profile}}
