apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveliness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enable: true
  ingress:
    - https://soknadsfillager.nais.preprod.local
    - https://app-q0.adeo.no/soknadsfillager