apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8090
  liveliness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingress:
    - "https://soknadsfillager.nais.preprod.local/"
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
  env:
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
    - name: SRVSOKNADSFILLAGER_USERNAME
      value: srvsoknadsfillager
    - name: DATABASE_HOST
      value: TBD
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: soknadsfillager-db-dev
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss
