apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveliness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enable: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingress:
    - "https://adeo.no/soknadsfillager"
    - "https://soknadsfillager.nais.adeo.no/"
    - "https://app.adeo.no/soknadsfillager" # benyttes for at legacy skal kunne bruke tjenester
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
  env:
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
