apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveliness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resource:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsfillager.nais.preprod.local"
    - "https://soknadsfillager.dev-fss.nais.io"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadsfillager
      - mountPath: /var/run/secrets/nais.io/arkiverer
        kvPath: /serviceuser/data/dev/srvsoknadarkiverer
      - mountPath: /var/run/secrets/nais.io/kv
        kvPath: /kv/preprod/fss/soknadsfillager/default
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev

  env:
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
    - name: DATABASE_HOST
      value: b27dbvl009.preprod.local
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: soknadsfillager-db-dev
    - name: VAULT_DB_PATH
      value: postgresql/preprod-fss
    - name: APPLICATION_PROFILE
      value: dev
