apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: default
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveliness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enable: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsfillager.nais.adeo.no"
    - "https://soknadsfillager.prod-fss.nais.io"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvsoknadsfillager
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/prod

  env:
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: APP_VERSION
      value: {{ app_version }}
    - name: DATABASE_HOST
      value: A01DBVL020.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: soknadsfillager-db
    - name: VAULT_DB_PATH
      value: postgresql/prod-fss/
    - name: APPLICATION_PROFILE
      value: prod
