apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsfillager
  namespace: q1
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 9042
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://soknadsfillager-q1.dev.intern.nav.no"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvsoknadsfillager
      - mountPath: /secrets/innsending-data
        kvPath: secret/team-soknad/innsending/basicauth

  env:
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_HOST
      value: b27dbvl009.preprod.local
    - name: DATABASE_NAME
      value: soknadsfillager-db-q1
    - name: VAULT_DB_PATH
      value: postgresql/preprod-fss
    - name: APPLICATION_PROFILE
      value: dev
