apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: {{namespace}}
  labels:
    team: team-soknad
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "320M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 9042
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingress}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{service-user-path}}
      - mountPath: /secrets/innsending-data
        kvPath: secret/team-soknad/innsending/basicauth

  env:
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_HOST
      value: {{database-host}}
    - name: DATABASE_NAME
      value: {{database-name}}
    - name: VAULT_DB_PATH
      value: {{vault-db-path}}
    - name: APPLICATION_PROFILE
      value: {{profile}}
