openapi: 3.0.3
info:
  description: A file storage to which a client can upload, retrieve and delete files.
  version: 2.0.0
  title: Soknadsfillager
  contact:
    name: team-soknad
    email: team-soknad@nav.no
  license:
    name: MIT License
    url: https://github.com/navikt/soknadsfillager/blob/main/LICENSE
tags:
  - name: files
    description: Access to the file storage
  - name: health
    description: Application health endpoint

paths:
  /files:
    post:
      summary: Add new files to the file storage.
      description: Adds new files to the file storage. If a file already exists with the given id, the old file is overwritten. A file entry with no file content is not added
      operationId: addFiles

      requestBody:
        description: Files that will be added to the storage.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/FileData"
        required: true

      parameters:
        - in: header
          name: X-innsendingId
          description: Tracing id that will be used in logging statements.
          example: 92ee15dd-dc49-4c95-b9b6-6224bae088a0
          required: false
          schema:
            type: string
        - in: header
          name: X-dryRun
          description: >
            If this value is passed in, the service will only log the requests sent, nothing will be
            stored in the database. Omit setting this header to store properly in the database.
          example: enabled
          required: false
          schema:
            type: string
            default: null

      responses:
        200:
          description: Successful operation
      tags:
        - files

  /files/{ids}:
    get:
      summary: Finds files with given ids.
      description: Given a list of ids, this endpoint returns all files associated with those ids.
      operationId: findFilesByIds

      parameters:
        - name: ids
          in: path
          description: A list of ids of files to be retrieved from the file storage.
          required: true
          schema:
            type: array
            items:
              type: string
          style: simple

        - name: metadataOnly
          in: query
          description: Fetches only metadata (not the content) of the file ids.
          required: false
          schema:
            type: boolean

        - name: X-innsendingId
          in: header
          description: Tracing id that will be used in logging statements.
          example: 92ee15dd-dc49-4c95-b9b6-6224bae088a0
          required: false
          schema:
            type: string

      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FileData"
      tags:
        - files

    delete:
      summary: Deletes files with given ids.
      description: Deletes the files with the given ids from the file storage. References to the files will still be kept, indicating that they once existed, but their content will be deleted. If any id provided does not match a file in the file storage, the response will still be 200.
      operationId: deleteFiles

      parameters:
        - name: ids
          in: path
          description: Given a list of ids (strings), this endpoint returns all files associated with those ids.
          required: true
          schema:
            type: array
            items:
              type: string
          style: simple

        - in: header
          name: X-innsendingId
          description: Tracing id that will be used in logging statements.
          example: 92ee15dd-dc49-4c95-b9b6-6224bae088a0
          required: false
          schema:
            type: string

      responses:
        200:
          description: The requested files were deleted.
      tags:
        - files


  /health/ping:
    get:
      summary: Pings the application to see if it responds
      description: Pings the application to see if it responds
      operationId: ping

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is responding
      tags:
        - health

  /health/isAlive:
    get:
      summary: Checks if the application and its dependencies up
      description: Checks if the application and its dependencies are up and running.
      operationId: isAlive

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is alive
        '500':
          description: The application or one of its dependencies are not up and running.
      tags:
        - health

  /health/isReady:
    get:
      summary: Checks if the application is ready to accept traffic
      description: Checks if the application is ready to accept traffic.
      operationId: isReady

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is ready
        '503':
          description: The application or one of its dependencies are not ready
      tags:
        - health


components:
  schemas:
    FileData:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Unique id of the file
          example: 2f9b8d25-1056-4827-8ddd-cedab7fafaaf
        content:
          type: string
          format: byte
          nullable: true
          description: Byte array of the file content
          example: Byte array with file content
        createdAt:
          type: string
          format: date-time
          nullable: true
          description: Creation date and time in UTC
          example: 2021-12-03T14:10:00Z
        status:
          type: string
          description: current state of the file. Can be `deleted`, `not-found`, `ok`
          example: not-found
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

externalDocs:
  description: Documentation of the whole archiving system
  url: https://github.com/navikt/archiving-infrastructure/wiki
