name: Manually triggered deployment (alerts)
run-name: Manual ${{ github.event.inputs.environment }} alert deploy of branch ${{ github.head_ref || github.ref_name }}
permissions:
  contents: "read"
  id-token: "write"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod

jobs:
  dev-deploy:
    if: github.event.inputs.environment == 'preprod'
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yml
          VARS: .nais/preprod-alert.json

  prod-deploy:
    if: github.event.inputs.environment == 'prod'
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
          VARS: .nais/prod-alert.json
